# Используем официальный образ Node.js
FROM node:22.14.0

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json (если есть)
COPY . /app/

# Открываем порт 5173
EXPOSE 5173

# Устанавливаем зависимости
RUN npm install


# Запускаем приложение
CMD ["npm", "run", "dev"]